app/blueprints/auth.py
from flask import render_template, Blueprint, request, jsonify, redirect, url_for

from app.extensions import db
from app.libs.error_code import UserexistError
from app.libs.token import generate_auth_token, combine_token_info
from app.models import User


auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """Log in from website.

    It is easy to log in by third party.

    .. note::
        Due to Facebook only let authorizing by 'https' protocal, and this is a 'http' protocal website demo, so you can not log in by Facebook successfully.

    :url: http://3.9.215.67:9999/login
    :return: token, expiration, scope
    """
    if request.method == 'POST':
        data = request.form
        email = data['email']
        password = data['password']
        identity = User.verify(email, password)
        token, expires_in = generate_auth_token(identity['uid'],
                                                identity['scope'],
                                                expiration=1800)
        t = combine_token_info(token, expires_in, scope=identity['scope'] )
        return jsonify(t), 201
    return render_template('_login.html')

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    """Register from website.

    :url: http://3.9.215.67:9999/register
    :return: result
    """
    if request.method == 'POST':
        data = request.form
        email = data['email']
        password = data['password']
        user = User.query.filter_by(email=email).first()
        if not user:
            user = User(email=email)
            user.password = password
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('.login'))
        return UserexistError()
    return render_template('_register.html')

app/blueprints/oauth.py
import os
from flask import Blueprint, url_for, jsonify
from app.extensions import oauth, db
from app.libs.error_code import AuthFailed
from app.libs.token import generate_auth_token, combine_token_info
from app.models import User

oauth_bp = Blueprint('oauth', __name__)

github = oauth.register(
    name='github',
    client_id= os.getenv('GITHUB_CLIENT_ID'),
    client_secret= os.getenv('GITHUB_CLIENT_SECRET'),
    access_token_url='https://github.com/login/oauth/access_token',
    access_token_params=None,
    authorize_url='https://github.com/login/oauth/authorize',
    authorize_params=None,
    api_base_url='https://api.github.com/',
    client_kwargs={'scope': 'user:email'},
)

google = oauth.register(
    name='google',
    client_id=os.getenv('GOOGLE_CLIENT_ID'),
    client_secret=os.getenv('GOOGLE_CLIENT_SECRET'),
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_params=None,
    authorize_url='https://accounts.google.com/o/oauth2/v2/auth',
    authorize_params=None,
    api_base_url='https://www.googleapis.com/oauth2/v3/',
    client_kwargs={'scope': 'openid email profile'},
)

facebook = oauth.register(
    name='facebook',
    client_id=os.getenv('FACEBOOK_CLIENT_ID'),
    client_secret=os.getenv('FACEBOOK_CLIENT_SECRET'),
    access_token_url='https://graph.facebook.com/v2.12/oauth/access_token',
    access_token_params=None,
    authorize_url='https://www.facebook.com/v2.12/dialog/oauth',
    authorize_params=None,
    api_base_url='https://graph.facebook.com/v2.12',
    client_kwargs={'scope': 'email'}
)


twitter = oauth.register(
    name='twitter',
    client_id=os.getenv('TWITTER_CLIENT_ID'),
    client_secret=os.getenv('TWITTER_CLIENT_SECRET'),
    request_token_url='https://api.twitter.com/oauth/request_token',
    request_token_params=None,
    access_token_url='https://api.twitter.com/oauth/access_token',
    access_token_params=None,
    authorize_url='https://api.twitter.com/oauth/authenticate',
    authorize_params=None,
    api_base_url='https://api.twitter.com/1.1/',
    client_kwargs=None
)

providers = {
    'github': github,
    'twitter': twitter,
    'facebook':facebook,
    'google':google

}

profile_endpoints = {
    'github': 'user',
    'google': 'userinfo',
    'facebook': 'user',
    'twitter': 'account/verify_credentials.json?include_email=true'
}


def get_social_profile(provider, access_token):
    profile_endpoint = profile_endpoints[provider.name]
    resp = provider.get(profile_endpoint, token=access_token)
    profile = resp.json()

    if provider.name == 'twitter':
        email = profile.get('email')
    elif provider.name == 'google':
        email = profile.get('email')
    else:
        email = profile.get('email')
    return email


@oauth_bp.route('/login/<provider_name>')
def login(provider_name):
    # provider = oauth.create_client(provider_name)
    redirect_uri = url_for('.authorize', provider_name=provider_name, _external=True)
    return providers[provider_name].authorize_redirect( redirect_uri)

@oauth_bp.route('/authorize/<provider_name>')
def authorize(provider_name):
    provider = oauth.create_client(provider_name)
    token = provider.authorize_access_token()
    if token is None:
        raise AuthFailed()

    email = get_social_profile(provider,token)
    user = User.query.filter_by(email=email).first()
    if not user:
        user = User(
            email=email,
            register_from=provider_name
        )
        db.session.add(user)
        db.session.commit()
    identity = user.verify_oauth(email)
    expiration = 3600
    token,expires_in = generate_auth_token(identity['uid'],
                                provider_name.capitalize(),
                                identity['scope'],
                                expiration)
    t = combine_token_info(token=token, scope= identity['scope'], exp=expires_in)
    return jsonify(t), 201

app/templates/_login.html
{% extends 'base.html' %}

{% block content %}

<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <div class="content">
                Log in to your account
            </div>
        </h2>
        <div class="ui">
            <form class="ui large form" method="post">
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            <input type="text" name="email" placeholder="E-mail address">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i>
                            <input type="password" name="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="field">
                        <input class="ui fluid large teal submit button" type="submit" value="Log in">
                    </div>
                    <div class="field">
                        <a class="ui button fluid gap" href="{{ url_for('auth.register') }}">
                            Sign Up
                        </a>
                    </div>
                </div>
              <div class="ui error message"></div>
            </form>
        </div>

        <div class="ui">
            <a class="link" href="{{ url_for('oauth.login', provider_name='facebook') }}">
                <button class="ui facebook button fluid gap">
                    <i class="facebook icon"></i>
                    Facebook
                </button>
            </a>
            <a class="link" href="{{ url_for('oauth.login', provider_name='twitter') }}">
                <button class="ui twitter button fluid gap">
                    <i class="twitter icon"></i>
                    Twitter
                </button>
            </a>
            <a class="link" href="{{ url_for('oauth.login', provider_name='github') }}">
                <button class="ui github button fluid black gap">
                    <i class="github icon"></i>
                    Github
                </button>
            </a>
            <a href="{{ url_for('oauth.login', provider_name='google') }}">
                <button class="ui google button fluid red gap">
                    <i class="google icon"></i>
                    Google
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/_register.html
{% extends 'base.html' %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <div class="content">
                Register
            </div>
        </h2>
        <form class="ui large form" method="post">
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" name="email" placeholder="E-mail address">
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" name="password" placeholder="Password">
                    </div>
                </div>
                <div class="field">
                        <input class="ui fluid large teal submit button" type="submit" value="Sign up">
                </div>
            </div>
          <div class="ui error message"></div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>API DEMO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>

{% block content %}{% endblock %}

<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>

</body>
</html>